#+ endpoint: http://ejprd.fair-dtls.surf-hosted.nl:8085/blazegraph/namespace/kb/sparql
#+ endpoint_in_url: False
#+ defaults:
#+   - theme: http://www.orpha.net/ORDO/Orphanet_586

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcat-ext: <http://purl.org/biosemantics-lumc/ontologies/dcat-extension/>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

# Count the number of biobanks/patient registries for Cystic Fibrosis
SELECT (COUNT(DISTINCT ?resource) AS ?resources) WHERE { 
  
   # Select theme = "Cystic fibrosis" rare disease (Orphanet_586)
   #VALUES (?_theme_iri) {(<http://www.orpha.net/ORDO/Orphanet_586>)}
  
   ?resource a ?resourceType ;
             dcat:theme ?_theme_iri .
  
  FILTER ((?resourceType = dcat-ext:Biobank) || (?resourceType = dcat-ext:PatientRegistry))
}
