#+ endpoint: http://ejprd.fair-dtls.surf-hosted.nl:8085/blazegraph/namespace/kb/sparql
#+ endpoint_in_url: False
#+ description: Get count of number of resources (biobank and patient registries) described in this endpoint.


PREFIX dcat-ext: <http://purl.org/biosemantics-lumc/ontologies/dcat-extension/>

# Count the total number of biobanks/patient registries
SELECT (COUNT(DISTINCT ?resource) AS ?resources) WHERE { 
  
  ?resource a ?resourceType .
  
  FILTER ((?resourceType = dcat-ext:Biobank) || (?resourceType = dcat-ext:PatientRegistry))
}
