#+ endpoint: http://ejprd.fair-dtls.surf-hosted.nl:8085/blazegraph/namespace/kb/sparql
#+ endpoint_in_url: False
#+ description: Get response to a query for a certain rare disease (resources).
#+ defaults:
#+   - theme: http://www.orpha.net/ORDO/Orphanet_586

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcat-ext: <http://purl.org/biosemantics-lumc/ontologies/dcat-extension/>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fdo: <http://rdf.biosemantics.org/ontologies/fdp-o#> 

SELECT DISTINCT ?resource ?title ?description ?homepage ?resourceType WHERE { 
  
   # Select theme = "Cystic fibrosis" rare disease (Orphanet_586)
   #VALUES (?_theme_iri) {(<http://www.orpha.net/ORDO/Orphanet_586>)}
  
   ?resource a ?resourceType ;
             dcat:theme ?_theme_iri;
             dcterm:description ?description;
             dcterm:title ?title; 
             dcat:landingPage ?homepage;                                                                                  
             fdo:metadataIdentifier [ dcterm:identifier ?id].
  
  FILTER ((?resourceType = dcat-ext:Biobank) || (?resourceType = dcat-ext:PatientRegistry))
}
