#+ endpoint: http://ejprd.fair-dtls.surf-hosted.nl:8085/blazegraph/namespace/kb/sparql
#+ endpoint_in_url: False
#+ defaults:
#+   - orphaCode: Orphanet_586

PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcat-ext: <http://purl.org/biosemantics-lumc/ontologies/dcat-extension/>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX fdo: <http://rdf.biosemantics.org/ontologies/fdp-o#>

SELECT (COUNT(DISTINCT ?resource) AS ?resources) WHERE { 
  
   BIND( IRI(CONCAT("http://www.orpha.net/ORDO/",?_orphaCode)) as ?theme)
  
   ?resource a ?resourceType ;
             dcat:theme ?theme;
             dcterm:description ?description;
             dcterm:title ?title; 
             dcat:landingPage ?homepage;                                                                                  
             fdo:metadataIdentifier [ dcterm:identifier ?id].
  
  FILTER ((?resourceType = dcat-ext:Biobank) || (?resourceType = dcat-ext:PatientRegistry))
}
